/**:
  ros__parameters:
    min_longitudinal_offset: 0.49
    max_longitudinal_offset: 0.52
    min_lateral_offset: -0.13
    max_lateral_offset: 0.19
    min_height_offset: 0.23
    max_height_offset: 0.29
